### PR TITLE
Move meshes and models from drake to drake_models

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Towards https://github.com/RobotLocomotion/drake/issues/19078 and https://github.com/RobotLocomotion/drake/issues/11913.

See https://github.com/RobotLocomotion/drake/pull/19160 for the sibling pull request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/23)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for feature review, please to match up with https://github.com/RobotLocomotion/drake/pull/19160.

**Review by rpoyner-tri — APPROVED** [review]
:lgtm: conversion scripts question

I verified that (almost) all of the files that came from drake were copied without changes, and the few that were changed only had internal file paths updated.

> Reviewed 316 of 316 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/23#-:-NSmBHf7BqYxIrq7VEd-:b-kaa5yr)* status: 1 unresolved discussion, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/23#-NSmBIRw-HJmxgHYIAbW:-NSmBIRw-HJmxgHYIAbX:b3kcmcv) (no related file):*
Do the conversion script files need more documentation? I assume they are not needed to be used, but rather are a record of the derivation of some of the files.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/23)* status: 1 unresolved discussion, platform LGTM from [rpoyner-tri] (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/23#-NSmBIRw-HJmxgHYIAbW:-NSmBxGK3qiqhyHJqHjG:b5fbxm8) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

Do the conversion script files need more documentation? I assume they are not needed to be used, but rather are a record of the derivation of some of the files.
</blockquote></details>

I think you're talking about some of the Atlas files.  Is that right?

I think only moved those without any edits.  If I made them _worse_ (e.g., filenames are wrong now) then let me know and I should fix that here.

If your observation is that some old pre-TRI stuff from 2014 no longer meets our standards, I would agree but I don't think that's relevant to this PR.

___

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/23)* status: :shipit: complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/23#-NSmBIRw-HJmxgHYIAbW:-NSmDxrM8s7J2ZZeLbkZ:b-7qqgkb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think you're talking about some of the Atlas files.  Is that right?

I think only moved those without any edits.  If I made them _worse_ (e.g., filenames are wrong now) then let me know and I should fix that here.

If your observation is that some old pre-TRI stuff from 2014 no longer meets our standards, I would agree but I don't think that's relevant to this PR.
</blockquote></details>

fair.

___

**Pull request merged**
