### PR TITLE
Add WSG50 with deformable bubble gripper

### PR DESCRIPTION
**Pull request by xuchenhan-tri**
Twin Drake PR: https://github.com/RobotLocomotion/drake/pull/21240

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/61)

### CODE REVIEW

**Review by xuchenhan-tri — COMMENTED** [review]
+@jwnimmer-tri for reviews please? I figured you might have opinions on how I split the models files across models/ and drake/

Sherm already reviewed the content of the sdf file.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/61#-:-NufSZoICdy8bguWYJrq:b-hg1baa)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
For the files being added here, the file arrangement / choice of directories looks good to me.  I don't have time to review further -- and generally same feature reviewer should do both twin PRs anyway.

In terms of which files go where between drake vs drake_models, the invariant we want is that meshes live in this repository, and any sdformat / urdf / mjcf files that cite those meshes live here as well (so that e.g. renaming a mesh file is not a cross-repo twin PR change).

**Review by xuchenhan-tri — COMMENTED** [review]
> In terms of which files go where between drake vs drake\_models, the invariant we want is that meshes live in this repository, and any sdformat / urdf / mjcf files that cite those meshes live here as well

That makes sense and is mostly respected by my PRs. The only sticking point is that I left the teddy bear mesh in the drake repo. The size of the dir remains under 100kB though.

+@sherm1 for review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/61#-:-NufV88vDaqBw8dYituL:busu1ay)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by sherm1 — APPROVED** [review]
-@jwnimmer-tri
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/61#-:-NufYus51ljS5t7KQU_A:bpo47rf)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
In #62, I'm asking Sean to fix the filenames here.  When there are lots of models in the same assets subdir, names like `dots.png` and `dot_pattern.mtl` are too difficult to pair with their parent.  They should have been `textured_bubble.mtl` and `textured_bubble.png`.

**Pull request merged**
