### PR TITLE
[franka_description] Vastly improve visual meshes

### LINKED ISSUE #47: [franka_description] obj files with too many materials
See the description at https://github.com/RobotLocomotion/drake/issues/19935.

This will probably become moot as of #44, but logging here for tracking anyway.

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This changes out all meshes except for the finger.

The `models/franka_description/meshes/visual` directory increases from 11 MB to 17 MB.

As part of the refresh, this also removes the trademarks in the visuals.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21410

Closes #47.

TRI note: These files are a sync from Anzu as of `3558b38f6672e31b999ded0f30ae64ca00617f19`.

---

Before:

image

After:

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/66)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 78 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/66#-:-NxP8vvdE4ktB2yoMAmo:bg7igk9)* status: all discussions resolved, platform LGTM missing

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/66#-:-NxPAV1f0ct1nM3YGZCU:bybe5xg)* status: all discussions resolved, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @DamrongGuoy and @sherm1)

**Review by sherm1 — APPROVED** [review]
Damrong says the changes look good. I took a quick scan through the files and didn't see anything obviously weird, so: platform :lgtm:

> Reviewed 78 of 78 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/66#-:-NxPZgqD8z-pCbEKtNmq:be4nctx)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

**Pull request merged**
