### PR TITLE
Add TRI yellow bell pepper mesh files

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
+@xuchenhan-tri for platform review (Wednesday schedule), please.

CC: @russtedrake @rcory 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19#-:-NCTE7SPB882UZuHBzhH:blo2xgm)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @xuchenhan-tri)

**Comment by jwnimmer-tri** [comment]
Please see https://drake.mit.edu/model_version_control.html for the PR process.  Every PR to `models` needs a concurrent twin PR to Drake that uses it.

**Review by DamrongGuoy — COMMENTED** [review]
@jwnimmer-tri  Thank you for the pointer.  I'll change [Drake PR 17959](https://reviewable.io/reviews/robotlocomotion/drake/17959) to use these model files now. Right now I'm just copying them.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19#-:-NCVMXwJ8viKwmrwXs3O:biw8rez)* status: all discussions resolved, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @xuchenhan-tri)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCVzpOD0IarZRLMsEcK:-NCVzpOE70ISBONMj1_q:bum4wjq) (no related file):*
Set to Working on [Drake PR 17959](https://reviewable.io/reviews/robotlocomotion/drake/17959)

___

**Review by xuchenhan-tri — CHANGES_REQUESTED** [review]
Looks good to me. I'll give the stamp when the corresponding Drake PR is reviewed.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19#-:-NCW2YM0DzNuoS9sw182:b-vhe7eo)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCW377N5nScl4TACo6i:-NCW377N5nScl4TACo6j:bba5ey9) (no related file):*
minor, A brief README would be helpful here.

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCWML7ZEyHJnJx0d819:-NCWML7_58XtBdxZeOjw:b5wfwx2) (no related file):*
I don't think empty subdirectories (i.e., two level of directory hierarchy) are warranted for this repository, especially when there is only one vegetable so far.  I would like to advocate for either `veggies` or `bell_peppers` as the _sole_ and top-level directory in this PR.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCWML7ZEyHJnJx0d819:-NCWqFBX2h13IZbfzmkq:bd8edwv) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think empty subdirectories (i.e., two level of directory hierarchy) are warranted for this repository, especially when there is only one vegetable so far.  I would like to advocate for either `veggies` or `bell_peppers` as the _sole_ and top-level directory in this PR.
</blockquote></details>

I see.  I was following the `dishes`.
```
dishes/
dishes/bowls
dishes/bowls/evo_bowl.README.txt
dishes/bowls/evo_bowl_no_mtl.obj
dishes/bowls/LICENSE
```

I do agree that one level would be easier. Set to Working.

___

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy, @jwnimmer-tri, and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCWML7ZEyHJnJx0d819:-NCWxNNs-KvMBVD2-At6:b-r4172n) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

I see.  I was following the `dishes`.
```
dishes/
dishes/bowls
dishes/bowls/evo_bowl.README.txt
dishes/bowls/evo_bowl_no_mtl.obj
dishes/bowls/LICENSE
```

I do agree that one level would be easier. Set to Working.

</blockquote></details>

Done. Keep `veggies/`, no `veggies/bell_peppers/`.

___

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 3 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCW377N5nScl4TACo6i:-NCX1Yee47zXC4B2JNFm:bnyylye) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Is the README ok now?
</blockquote></details>

Looks good to me, thanks.

___
___
*[`veggies/README.md` line 5 at r6](https://reviewable.io/reviews/robotlocomotion/models/19#-NCX1SMw6tlfmTgKO6W-:-NCX1SMw6tlfmTgKO6W0:b2nhbfk) ([raw file](https://github.com/robotlocomotion/models/blob/0fd6eb4b3bba6dd044ef43367cba38675483678f/veggies/README.md#L5)):*
> ```Markdown
> Non-convex meshes of a yellow bell pepper.
> 
> The obj file and its supported mtl and png files are for visual.
> ```

BTW



_Suggestion:_
```Markdown
supporting
```
___
*[`veggies/README.md` line 15 at r6](https://reviewable.io/reviews/robotlocomotion/models/19#-NCX15l18eoifd_F3SSI:-NCX15l18eoifd_F3SSJ:b-ndxgmp) ([raw file](https://github.com/robotlocomotion/models/blob/0fd6eb4b3bba6dd044ef43367cba38675483678f/veggies/README.md#L15)):*
> ```Markdown
> ```
> 
> The vtk file is a tetrahedral volume mesh for compliant hydroelastic contact model.
> ```

BTW, 
1. the tet mesh is generic and doesn't necessarily need to be used for compliant hydro.
2. Is the obj the surface of the vtk?

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy and @xuchenhan-tri)

___
*[`veggies/README.md` line 5 at r6](https://reviewable.io/reviews/robotlocomotion/models/19#-NCX1SMw6tlfmTgKO6W-:-NCXgBCY6SwIFi33vqiZ:boyexbg) ([raw file](https://github.com/robotlocomotion/models/blob/0fd6eb4b3bba6dd044ef43367cba38675483678f/veggies/README.md#L5)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW
</blockquote></details>

Done. Thanks.
___
*[`veggies/README.md` line 15 at r6](https://reviewable.io/reviews/robotlocomotion/models/19#-NCX15l18eoifd_F3SSI:-NCXgDmQ17e8oT8osQgS:b2l7djq) ([raw file](https://github.com/robotlocomotion/models/blob/0fd6eb4b3bba6dd044ef43367cba38675483678f/veggies/README.md#L15)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, 
1. the tet mesh is generic and doesn't necessarily need to be used for compliant hydro.
2. Is the obj the surface of the vtk?
</blockquote></details>

Done. Yes and yes. I added the comments.

**Review by xuchenhan-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 1 unresolved discussion, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @DamrongGuoy)

___
*[`veggies/README.md` line 21 at r7](https://reviewable.io/reviews/robotlocomotion/models/19#-NCqs1K9AV4WD6B9tQSW:-NCqs1K9AV4WD6B9tQSX:bps3xte) ([raw file](https://github.com/robotlocomotion/models/blob/e2306ab515f4b05ef63a77bd25c147e30e5d6705/veggies/README.md#L21)):*
> ```Markdown
> ./yellow_bell_pepper_no_stem_low.vtk
> ```
> ```

Set to Working. Remind me to document the bounding box of the bell pepper.

Having the bounding box will simplify the setup of the simulation a lot.

**Review by DamrongGuoy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: 2 unresolved discussions, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCVzpOD0IarZRLMsEcK:-NGOeOO6EwrQzHW8Pr63:b8fkfpj) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Set to Working on [Drake PR 17959](https://reviewable.io/reviews/robotlocomotion/drake/17959)
</blockquote></details>

Drake PR [17959](https://reviewable.io/reviews/RobotLocomotion/drake/17959) got lgtm now. @xuchenhan-tri could you please approve this `models` PR, please?

___

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19#-:-NGOz4fG9DTirnWHulHH:bnfp4nl)* status: 1 unresolved discussion, platform LGTM missing

**Review by xuchenhan-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19)* status: all discussions resolved, platform LGTM missing (waiting on @DamrongGuoy)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/19#-NCVzpOD0IarZRLMsEcK:-NGOzJTg0inEVzRmqwll:bb6un1j) (no related file):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

Drake PR [17959](https://reviewable.io/reviews/RobotLocomotion/drake/17959) got lgtm now. @xuchenhan-tri could you please approve this `models` PR, please?
</blockquote></details>

Done

___

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/19#-:-NGSZjNoB38vBKECCZJr:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @DamrongGuoy)

**Pull request merged**
