### PR TITLE
Convert obj2gltf on visual meshes on *everything*

### LINKED ISSUE #44: Bulk glTF conversion
Per https://github.com/RobotLocomotion/drake/issues/20935, we want nearly all of our models to use gltf (not obj) for visual meshes.

Note that proximity meshes (if any?) should **not** be converted to gltf.

All gltfs with png file should also have ktx2 textures available (gltf-used but not gltf-required).

This ticket will track the conversion process:
- [ ] allegro hand #62
- [x] #58
- [ ] dishes #62
   - [x] Waiting on #60
- [ ] franka_description #62
   - Converted, but they can be replaced by Anzu's as we see fit. If we do so, confirm with legal.
- [x] #36
- [ ] jaco_description #62
- [ ] manipulation_station and realsense2_description #62
- [ ] pr2_description #62
  - This model is not used by Drake.  The only testing required is just to run model_visualizer.
- [ ] skydio_2 #62
  - Just add the gltf for now (and switch this repo's urdf to cite it).  Don't delete the obj yet -- we have a deprecated URDF file in Drake that will continue to refer to the obj until 2024-05-01.
- [x] tri_homecart
- [ ] ur_description #62
   - Instead of converting the obj, should we just use the Anzu gltfs for this?  (If yes, also need to run by TRI legal first.)
- [ ] veggies #62
   - [x] Waiting on #60
   - Converted locally. Consider replacing it with Anzu gltfs.
- [ ] wsg_50_description #62
- [x] #45

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Updates all of the remaining geometry in one huge chunk.

Each directory gets its own commit to facilitating possible reversion of single model files.

Closes #44.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
Visualize via:
`bazel run //tools:model_visualizer -- package://drake_models/allegro_hand_description/urdf/allegro_hand_description_right.urdf`

The obj and glTF representations are not perfect, but reasonable. For example:

OBJ of `allegro_hand_description_right.urdf`


glTF of same:


> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62#-:-NufWimM0rWTSL5OWmsT:b-ov80ux)* status: all discussions resolved, platform LGTM missing

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: 1 unresolved discussion, platform LGTM missing

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/62#-Nv3odTSD0fO1I3MlznJ:-Nv3odTTArptHktOuOVN:biclxnz) (no related file):*
Drake's PR testing on this is https://github.com/RobotLocomotion/drake/pull/21285.

___

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint on commit messages overview.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62#-:-NvCThi4EafCnCJ5Vs5t:b1vydss)* status: 5 unresolved discussions, platform LGTM missing (waiting on @SeanCurtis-TRI)

___
*[`-- commits` line 22 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCS3XN9LXjl6-pxbM6):*
nit I haven't looked in detail yet, but if this is saying that there are gltfs that are not cited by any URDF file today, then we should just delete those gltfs from this PR; git remembers.
___
*[`-- commits` line 46 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCSULc7DF6sa3-gv7X):*
nit Missing close-paren.
___
*[`-- commits` line 61 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCTPcoDn4DOfSnHBp6):*
nit Looks like ur got the ktx2 treatment as well?
___
*[`-- commits` line 69 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCTbmt0QmgkfFpqAjO):*
nit Looks like veggies got the ktx2 treatment as well?
___
*[`-- commits` line 79 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCShSTAdP30W6iyc6Z):*
nit We should be careful to not forgot about this.  Is is written down anywhere?  If not, maybe edit the twin Drake PR to have a TODO about this in some relevant render_gl place.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`-- commits` line 79 at r12](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvCShSTAdP30W6iyc6Z):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We should be careful to not forgot about this.  Is is written down anywhere?  If not, maybe edit the twin Drake PR to have a TODO about this in some relevant render_gl place.
</blockquote></details>

I've updated issue #20185 to include this in the checklist.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: all discussions resolved, platform LGTM missing

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
Checkpoint on everything but the jaco.

> Reviewed 43 of 301 files at r1, 44 of 44 files at r4, 18 of 18 files at r5, 64 of 64 files at r6, 4 of 4 files at r7, 6 of 6 files at r8, 34 of 34 files at r9, 8 of 8 files at r10, 25 of 25 files at r11, 7 of 7 files at r12, 8 of 8 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62#-:-NvI6nCC7MRaot8sQhed:bbbc6u6)* status: 9 unresolved discussions, platform LGTM missing (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvHu6Fk8av71End_QQq:-NvHu6Fk8av71End_QQr:b6l12pm) (no related file):*
Some documentation files are a bit stale (still mention obj & etc):
- `allegro_hand_description/LICENSE.TXT`
- `allegro_hand_description/meshes/README.txt`
- `franka_description/README.md`
- `jaco_description/README.md`
- `ur_description/README.md`
- `veggies/README.md`

Maybe also check all of the per-model text files to make sure they are accurate, in case I missed one.

___
___
*[`-- commits` line 47 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI-TGK7zk9lt1AkDFz):*
nit



_Suggestion:_
```
[pr2_description]
```
___
*[`-- commits` line 59 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI-tso1qi6J9CXBSBN):*
nit



_Suggestion:_
```
[realsense2_description]
```
___
*[`dishes/assets/evo_bowl.gltf` line 78 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvHwyc-8uzJQluKDezt:-NvHwyc-8uzJQluKDezu:bdri38h) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/dishes/assets/evo_bowl.gltf#L78)):*
> ```JSON
>       "name": "evo_bowl_no_mtl",
>       "byteLength": 179236,
>       "uri": "evo_bowl_no_mtl.bin"
> ```

nit I'm not sure that "no_mtl" in the name here is really buying us anything?  I suggest removing it. 

Or if not, then the gltf and bin filenames are inconsistent and the gltf should probably be "no_mtl" also?

There would also be an argument for renaming `evo_bowl_no_mtl.obj` to `evo_bowl_col.obj` to emphasize the collision mesh purpose, and align with the plate naming convention.
___
*[`dishes/assets/plate_8in_col.gltf` line 1 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvHzbwI34juYAQA2ayE:-NvHzbwI34juYAQA2ayF:bvi4cyw) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/dishes/assets/plate_8in_col.gltf#L1)):*
> ```JSON
> {
> ```

nit I understand this is named "_col" because that's what the obj was named, but I wonder if we should drop that now that it's solely a visual mesh?  I could go either way.
___
*[`ur_description/urdf/ur3e_cylinders_collision.urdf` line 28 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI2xbg-GZeu35S3gZ-:-NvI2xbg-GZeu35S3gZ0:buyubnr) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/ur_description/urdf/ur3e_cylinders_collision.urdf#L28)):*
> ```XML
>         <mesh filename="package://drake_models/ur_description/meshes/base.gltf"/>
>       </geometry>
>       <material name="LightGrey">
> ```

I would have thought all visual materials should have been removed?  (Ditto for all of the ur3e xml files.)
___
*[`wsg_50_description/meshes/dots.ktx2` line 0 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI5jE326vifUB9LjPq:-NvI5jE326vifUB9LjPr:b7khlfb) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/wsg_50_description/meshes/dots.ktx2#L0)):*
BTW "dots" is not a great name with dozens of other files around.  It should be `textured_bubble.png` (or at worst `textured_bubble_dots.png`) and ditto for ktx2 so that they all alpha-group with their siblings.  Ditto `dot_pattern.mtl` vs `textured_bubble.mtl`.  These defects are not new in this PR, but possibly worth cleaning up while we're here.
___
*[`wsg_50_description/sdf/schunk_wsg_50_deformable_bubble.sdf` line 37 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI4KJH5742rvtsNsGv:-NvI4KJH5742rvtsNsGw:bgek6fr) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/wsg_50_description/sdf/schunk_wsg_50_deformable_bubble.sdf#L37)):*
> ```
>           </mesh>
>         </geometry>
>         <material>
> ```

I would have thought all visual materials in this file should have been removed?

(Maybe our parser should warn about this, instead of only the render engine?)
___
*[`wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf` line 26 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI5FK687p50QWkuH17:-NvI5FK7DlExOpIVMpYp:bmwbgz4) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf#L26)):*
> ```
>           </mesh>
>         </geometry>
>         <material>
> ```

BTW Unwanted materials in this file?

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: both reviews.

> Reviewed 43 of 49 files at r3.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62#-:-NvI8G7H2YMei2kp7-jq:b9krqcj)* status: 10 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @SeanCurtis-TRI)

___
*[`jaco_description/meshes/finger_distal_alt.gltf` line 1 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI8BnIDDmpUASISh3D:-NvI8BnIDDmpUASISh3E:b-9bcpml) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/jaco_description/meshes/finger_distal_alt.gltf#L1)):*
> ```JSON
> {
> ```

nit I think this file is dead code?  (And has no bin)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: 4 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvHu6Fk8av71End_QQq:-NvY9O0lAnQMJ4yemJlY:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Some documentation files are a bit stale (still mention obj & etc):
- `allegro_hand_description/LICENSE.TXT`
- `allegro_hand_description/meshes/README.txt`
- `franka_description/README.md`
- `jaco_description/README.md`
- `ur_description/README.md`
- `veggies/README.md`

Maybe also check all of the per-model text files to make sure they are accurate, in case I missed one.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvY9Q3V6u9CRqMpmL-D:-NvY9Q3W5V041lNTFQ1K:b6t5m0r) (no related file):*
Blocking on another run of the Drake PR...stay tuned.

___
___
*[`ur_description/urdf/ur3e_cylinders_collision.urdf` line 28 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI2xbg-GZeu35S3gZ-:-NvY7zgo7QJUH6xYuCas:b-896fix) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/ur_description/urdf/ur3e_cylinders_collision.urdf#L28)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would have thought all visual materials should have been removed?  (Ditto for all of the ur3e xml files.)
</blockquote></details>

Done.
___
*[`wsg_50_description/sdf/schunk_wsg_50_deformable_bubble.sdf` line 37 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI4KJH5742rvtsNsGv:-NvY4ikM1QG7Dt1-Ahse:b-896fix) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/wsg_50_description/sdf/schunk_wsg_50_deformable_bubble.sdf#L37)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would have thought all visual materials in this file should have been removed?

(Maybe our parser should warn about this, instead of only the render engine?)
</blockquote></details>

Done.
___
*[`jaco_description/meshes/finger_distal_alt.gltf` line 1 at r13](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvI8BnIDDmpUASISh3D:-NvX_VOVDFsyNKrHre-w:bb6un1j) ([raw file](https://github.com/RobotLocomotion/models/blob/5c5fb727520ef2d5de146af01e7cbc57bfea43b2/jaco_description/meshes/finger_distal_alt.gltf#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I think this file is dead code?  (And has no bin)
</blockquote></details>

Done

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 23 of 23 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri]

**Review by jwnimmer-tri — COMMENTED** [review]
I think this is ready to merge now (remember to use a merge commit, not squash).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62#-:-NvYe8rN3J53zgziCS6k:bhu4xdm)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/62#-NvY9Q3V6u9CRqMpmL-D:-NvYe5XU8Fj0qmWrlAVU:b-yu9urd) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Blocking on another run of the Drake PR...stay tuned.
</blockquote></details>

Drake CI is happy (just one flake, which we can ignore).

___

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/62)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @SeanCurtis-TRI)

**Pull request merged**
