### PR TITLE
Fixes table top model

### PR DESCRIPTION
**Pull request by amcastro-tri**
Models with no inertia properties are dangerous. We add non-zero inertia properties to this model.

Note: consider removing this model? its just a simple box. Is it worth having it in this repository?

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/72)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
I can stay on as platform review.

+@DamrongGuoy for feature review, please.

> Is it worth having it in this repository?

Yes.  It's a tutorials model.  The fact that it does not have a PBR texture is a defect that will eventually be fixed by adding texture image(s) into this repo.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/72#-:-OEKHhre9xVqnvAYITZq:b3wasod)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee damrongguoy, platform LGTM missing (waiting on @amcastro-tri and @DamrongGuoy)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/72#-OEKHiYrBeBIiog2UGMX:-OEKHiYrBeBIiog2UGMY:b8zdar8) (no related file):*
Note that per https://drake.mit.edu/model_version_control.html you must open a Drake PR that bumps to this models sha and it must pass Drake CI prior to us merging this PR.  Otherwise, we won't have any automated testing for typos, etc.

**Review by amcastro-tri — COMMENTED** [review]
got it. Done.

Drake PR in flight [22321](https://github.com/RobotLocomotion/drake/pull/22321)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/72#-:-OEKOOxL7CLlt5KAupxk:b-w3a6ov)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee damrongguoy, platform LGTM missing (waiting on @DamrongGuoy and @jwnimmer-tri)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: platform.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/72#-:-OEKxEk69BoG-p-6FoQz:b-vtj4vo)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @amcastro-tri)

**Comment by DamrongGuoy** [comment]
BTW, I did SolidBoxWithMass() to confirm the numbers.  They are good!

**Pull request merged**
