### PR TITLE
[wsg_50_description] Move Drake files and punyo meshes into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The schunk_wsg_50_hydro_bubble is copied from Drake as of e7aa6fcd.

Some new README content is based off Drake's related README.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21231

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/53)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by DamrongGuoy — APPROVED** [review]
:lgtm:

CC: @joemasterjohn 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/53#-:-NuQUJBD74MaSdWdpudn:b50aja4)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for platform review per schedule (tomorrow), please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/53#-:-NuQbmoq8ejGe3H1Mhrs:b-75o053)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
isn't tomorrow @ggould-tri ?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/53#-:-NuQdTjG5Zy4rVayHeBo:b-814jv0)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Yup, sorry!

**Pull request merged**
