### PR TITLE
[pr2_description] Move Drake files into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This were copied from Drake as of 665721e9, notably copying the stl2obj output obj files, not the original stl files.

The only changes to the URDF are to the URL paths.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21185

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/41)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@RussTedrake for both reviews, please.

This is towards https://github.com/RobotLocomotion/drake/issues/13942 where we want to move all of our model files from Drake into this models menagerie (and convert them to glTF, etc).

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/41#-:-NtloHNI7QpCFUrwGh-u:b-7az0l2)* status: all discussions resolved, LGTM missing from assignee russtedrake, platform LGTM missing (waiting on @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/41)* status: 1 unresolved discussion, LGTM missing from assignee russtedrake, platform LGTM missing (waiting on @RussTedrake)

___
*[`pr2_description/LICENSE` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/models/41#-Ntlo5qw3f_Lq5r0aPfj:-Ntlo5qx47yGgMKVP6Sk:b-ijkv1i) ([raw file](https://github.com/RobotLocomotion/models/blob/42b5fe67dac0d47f35c968f80c0007d3e40a942b/pr2_description/LICENSE#L1)):*
> ```
> WIP We're not sure yet. Need to fix before merging this PR.
> ```

@RussTedrake you added the PR2 to Drake in https://github.com/RobotLocomotion/drake/commit/ab6eb2233ca9b03b6b8d3611d60d28b6c42e8dd1.  Where did the URDF and STL file come from originally, and what license are they under?

**Review by RussTedrake — COMMENTED** [review]
sorry for missing this til now.
:lgtm: x 2

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/41#-:-Nu8o2os0N59jKqUS1p5:b2bcp2u)* status: 1 unresolved discussion, platform LGTM from [russtedrake] (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`pr2_description/LICENSE` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/models/41#-Ntlo5qw3f_Lq5r0aPfj:-Nu8nTnT1ZwwUvMGVUhz:bip5p4h) ([raw file](https://github.com/RobotLocomotion/models/blob/42b5fe67dac0d47f35c968f80c0007d3e40a942b/pr2_description/LICENSE#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

@RussTedrake you added the PR2 to Drake in https://github.com/RobotLocomotion/drake/commit/ab6eb2233ca9b03b6b8d3611d60d28b6c42e8dd1.  Where did the URDF and STL file come from originally, and what license are they under?
</blockquote></details>

:gulp: sorry.  I'm pretty sure I would have gotten them from ROS.  https://github.com/PR2/pr2_common/ .  (If needed, one could potentially pull them over from there now, and clean things up; we would likely make a few different choices now).  Unfortunately, I don't see clear licensing in that quite mainstream repo.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/41)* status: 1 unresolved discussion, platform LGTM from [russtedrake] (waiting on @jwnimmer-tri and @RussTedrake)

___
*[`pr2_description/LICENSE` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/models/41#-Ntlo5qw3f_Lq5r0aPfj:-Nu9W03O0tYjKLMmdrhm:bo067ca) ([raw file](https://github.com/RobotLocomotion/models/blob/42b5fe67dac0d47f35c968f80c0007d3e40a942b/pr2_description/LICENSE#L1)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

:gulp: sorry.  I'm pretty sure I would have gotten them from ROS.  https://github.com/PR2/pr2_common/ .  (If needed, one could potentially pull them over from there now, and clean things up; we would likely make a few different choices now).  Unfortunately, I don't see clear licensing in that quite mainstream repo.
</blockquote></details>

Working

There is BSD listed [in the repo](https://github.com/PR2/pr2_common/blob/c36a5c9c8d5e97d2d53a7c75fa57a3257a7c63cc/pr2_description/package.xml#L10).  I'll update to match that here.

**Pull request merged**
