### PR TITLE
Fixes skydio model prop colors and normals.

### PR DESCRIPTION
**Pull request by RussTedrake**
Previously, the props rendered all black in meshcat. The png was just setting a color, anyhow, so I've removed the png and just set the color directly.
    
Previously, the props were invisible if you view the quadrotor from below. I've added additional faces to make the props double-sided.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/21)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
:lgtm: with nits.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/21#-:-NPK1X_gBoF_Jz4UHkMH:b-cwzrcn)* status: 2 unresolved discussions, platform LGTM missing (waiting on @RussTedrake)

___
*[`skydio_2/README.md` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/models/21#-NPK11Q4CdHCOH7duT2P:-NPK11Q4CdHCOH7duT2Q:b2ni8l0) ([raw file](https://github.com/RobotLocomotion/models/blob/d37a245b32f32127aa24442eb72197911bd346cb/skydio_2/README.md#L3)):*
> ```Markdown
> # Skydio 2
> 
> This .obj, .mtl, and .png file were contributed by Abe Bachrach from Skydio.
> ```

nit



_Suggestion:_
```Markdown
This .obj and .mtl file were contributed by Abe Bachrach from Skydio.
```
___
*[`skydio_2/README.md` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/models/21#-NPK0QqEBZfFhVp2GmUk:-NPK0QqEBZfFhVp2GmUl:bg1tk0y) ([raw file](https://github.com/RobotLocomotion/models/blob/d37a245b32f32127aa24442eb72197911bd346cb/skydio_2/README.md#L9)):*
> ```Markdown
>   propellers; previously the propellers were invisible from below.
> - The .png file was removed, and the .mtl file was manually edited to replace
>   the single color value from the .png directly into the .mtl file.
> ```

nit, add a newline, please.



_Suggestion:_
```Markdown
  the single color value from the .png directly into the .mtl file.
  
```

**Review by RussTedrake — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/21)* status: all discussions resolved, platform LGTM missing (waiting on @DamrongGuoy)

___
*[`skydio_2/README.md` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/models/21#-NPK11Q4CdHCOH7duT2P:-NPPoGHuE-pWIUBtaEce:b-896fix) ([raw file](https://github.com/RobotLocomotion/models/blob/d37a245b32f32127aa24442eb72197911bd346cb/skydio_2/README.md#L3)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`skydio_2/README.md` line 9 at r1](https://reviewable.io/reviews/RobotLocomotion/models/21#-NPK0QqEBZfFhVp2GmUk:-NPPoN0e8zktBqoaP5KX:b-896fix) ([raw file](https://github.com/RobotLocomotion/models/blob/d37a245b32f32127aa24442eb72197911bd346cb/skydio_2/README.md#L9)):*
<details><summary><i>Previously, DamrongGuoy (Damrong Guoy) wrote…</i></summary><blockquote>

nit, add a newline, please.
</blockquote></details>

Done.

**Comment by RussTedrake** [comment]
+@DamrongGuoy for platform review, to clear the status.

**Comment by RussTedrake** [comment]
+@DamrongGuoy for feature review, please.

**Comment by RussTedrake** [comment]
+@RussTedrake for platform review, I guess?
:lgtm:

**Pull request merged**
