### PR TITLE
[realsense2_description] Move Drake files into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/RobotLocomotion/drake/pull/21191

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/43)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/43)* status: 1 unresolved discussion, platform LGTM missing (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/43#-NtsBO0hBoQ3xJpdftAR:-NtsBO0hBoQ3xJpdftAS:b-4ln8vq) (no related file):*
Working

We will use a merge commit here (not squash).

___

**Review by jwnimmer-tri — COMMENTED** [review]
+@rpoyner-tri for both reviews, please.  Note that the commits are curated, which should help both the review and the git history later on.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/43#-:-NtsOxsW-QxPUmGUixAE:b-urc5m6)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/43#-:-Ntw0lZr99tzesm6cxec:bnfp4nl)* status: 2 unresolved discussions, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

___
*[`realsense2_description/urdf/customize.sed` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/models/43#-Ntw03DN7dIN-1AwK3-r:-Ntw03DN7dIN-1AwK3-s:b-1k7wyh) ([raw file](https://github.com/RobotLocomotion/models/blob/6f49d40d6b24074e1e5153a4f0238c511cec549f/realsense2_description/urdf/customize.sed#L1)):*
> ```sed
> s|$(find realsense2_description)/urdf/||;
> ```

nit TIL that `$` does not act as a special character, *unless* it is at the end of an expression (or subexpression (GNU)).  Maybe worth a comment?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/43)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/43#-NtsBO0hBoQ3xJpdftAR:-NtwFont6glV77Wmlry7:b-7x20hh) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

We will use a merge commit here (not squash).
</blockquote></details>

In progress.

___
___
*[`realsense2_description/urdf/customize.sed` line 1 at r3](https://reviewable.io/reviews/RobotLocomotion/models/43#-Ntw03DN7dIN-1AwK3-r:-NtwFo5eB860MpYcRMrq:bb6un1j) ([raw file](https://github.com/RobotLocomotion/models/blob/6f49d40d6b24074e1e5153a4f0238c511cec549f/realsense2_description/urdf/customize.sed#L1)):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

nit TIL that `$` does not act as a special character, *unless* it is at the end of an expression (or subexpression (GNU)).  Maybe worth a comment?
</blockquote></details>

Done

**Pull request merged**
