### PR TITLE
[tri_homecart] Convert visual meshes to glTF

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Companion PR: https://github.com/RobotLocomotion/drake/pull/21039.

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please.

**Review by SeanCurtis-TRI — APPROVED** [review]
There are a couple of defects in the model -- one predates this PR but the other is introduced by this PR. PTAL.

> Reviewed 26 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33#-:-NrfFlDHDmnDhNt0JnOe:b-gony5b)* status: 2 unresolved discussions, LGTM missing from assignee seancurtis-tri, platform LGTM missing (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfD0YI-eQb3e5WxwCF:-NrfD0YI-eQb3e5WxwCG:bcnkgsk) (no related file):*
BTW While this constitutes an upgrade, it isn't complete. A simple translation from obj to glTF leaves fidelity on the table. Do we have a task for an artist to come in after this and "sweeten" the models? (E.g., texture some of the other PBR parameters?) The wooden pieces would be clear beneficiaries of that. (And the cutting board has some unfortunate texture artifacts around its edge.)

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfDroY4qH7jnF7hZtd:-NrfDroY4qH7jnF7hZte:b-b5iatb) (no related file):*
FYI the model is flawed


We stack a number of the mounting plates. However, we have a gap at the bottom of the stack, and an extra plate at the top that is actually intersecting the robot arm's base. The proximity geometry for this box (represented as a single box) is in the correct place.Looking at master, it's clear that's a defect that predates this PR.

The model for the mount stack does *not* lie on the Wz = 0 plane, it floats above it. Without a keypad, I'm somewhat hampered in my ability to use blender, but it appears to be floating about 0.15 cm above the plane. If the geometry were to be moved (either in the .bin file and moved, or by adding a translation to the node in the .gltf file), I believe the stack would be corrected.

___
___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfB-09ABmIZuHlHVL6:b-or8f9u) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
> ```JSON
> 				"baseColorTexture":{
> 					"extensions":{
> 						"KHR_texture_transform":{
> ```

nit: This model is rejected by `RenderEngineVtk` and this extension is the reason given. Do we really want that behavior in a TRI-branded model?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33)* status: 1 unresolved discussion, LGTM missing from assignee seancurtis-tri, platform LGTM missing (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfDroY4qH7jnF7hZtd:-NrfUIwC0lPXtsjuzhrO:byx0q6c) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

FYI the model is flawed


We stack a number of the mounting plates. However, we have a gap at the bottom of the stack, and an extra plate at the top that is actually intersecting the robot arm's base. The proximity geometry for this box (represented as a single box) is in the correct place.Looking at master, it's clear that's a defect that predates this PR.

The model for the mount stack does *not* lie on the Wz = 0 plane, it floats above it. Without a keypad, I'm somewhat hampered in my ability to use blender, but it appears to be floating about 0.15 cm above the plane. If the geometry were to be moved (either in the .bin file and moved, or by adding a translation to the node in the .gltf file), I believe the stack would be corrected.
</blockquote></details>

Filed as #35, thanks.  I hadn't seen that before.

For a "convert file format" PR, I think keeping bug-for-bug compatibility is a good thing.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfD0YI-eQb3e5WxwCF:-NrfabPK3SZvJjG0r0Ae:bly3aii) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW While this constitutes an upgrade, it isn't complete. A simple translation from obj to glTF leaves fidelity on the table. Do we have a task for an artist to come in after this and "sweeten" the models? (E.g., texture some of the other PBR parameters?) The wooden pieces would be clear beneficiaries of that. (And the cutting board has some unfortunate texture artifacts around its edge.)
</blockquote></details>

That wasn't on my radar.  My aim is [drake#20932](https://github.com/RobotLocomotion/drake/issues/20932) where all of our models follow best practices for de-embedding their assets, and using glTF instead of OBJ for visuals.

Do you think we should have an issue for "curate Drake's models to demonstrate texturing best practices"?  If so, maybe file that as a separate feature request?

___
___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfU62t33-Nqsrb2Aw2:b-u1jxue) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: This model is rejected by `RenderEngineVtk` and this extension is the reason given. Do we really want that behavior in a TRI-branded model?
</blockquote></details>

Yikes!  Thanks, I didn't notice that.

Removed now.

**Review by SeanCurtis-TRI — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33)* status: 1 unresolved discussion, LGTM missing from assignee seancurtis-tri, platform LGTM missing (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfD0YI-eQb3e5WxwCF:-NrfkTRJ7IFqX8PP4-OM:b-18luft) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

That wasn't on my radar.  My aim is [drake#20932](https://github.com/RobotLocomotion/drake/issues/20932) where all of our models follow best practices for de-embedding their assets, and using glTF instead of OBJ for visuals.

Do you think we should have an issue for "curate Drake's models to demonstrate texturing best practices"?  If so, maybe file that as a separate feature request?
</blockquote></details>

I'd hesitate to use the phrase "demonstrate texturing best practices". That opens the door into evaluating *how* we texture things and questions of whether it is best practice or not. My emphasis would be more about:

 - Exercising the potential is there, showing that it can be exercised and it has an effect.
 - Best foot forward.

I'd like our models to look as nice as Drake can handle (whether they're done with "best texturing practices" is a different issue). For example, I started working on one of the robot arms to use glTF and was actively looking to make the model look better. I think it's worth having a feature request that the models in this repo look as good as possible, as we've implicitly branded them with Drake.

But it's definitely outside the scope of this PR.

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfDroY4qH7jnF7hZtd:-NrflF2hBDECR9n08lko:b-pbdqz3) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Filed as #35, thanks.  I hadn't seen that before.

For a "convert file format" PR, I think keeping bug-for-bug compatibility is a good thing.
</blockquote></details>

Agreed.

___
___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfgxVd5C8I4cUqUvZw:bf6ww3n) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Yikes!  Thanks, I didn't notice that.

Removed now.
</blockquote></details>

It's worth noting this will have a *palpable* effect on the appearance.



(this PR on the left, original on the right)

I got the sense that you didn't want to change appearance. Admittedly, the fact that its a glTF is going to change appearance (PBR vs Phong), but the wood texture change is independent of the lighting model. I just want to make sure you're aware that this is a consequence of this approach.

Ultimately, I'd assume there is a blender file that stands behind this glTF file. Ideally, I should be able to export that glTF file anew and reproduce what is here (which probably is more of an argument about keeping the blender files in a repo). But my main point here is that we now have a different model than we have elsewhere and it might be easy to accidentally stomp over this mindlessly because of these local changes.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33)* status: all discussions resolved, LGTM missing from assignee seancurtis-tri, platform LGTM missing (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfD0YI-eQb3e5WxwCF:-Nrfm3-E0lGx3TePC5iK:bncute7) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd hesitate to use the phrase "demonstrate texturing best practices". That opens the door into evaluating *how* we texture things and questions of whether it is best practice or not. My emphasis would be more about:

 - Exercising the potential is there, showing that it can be exercised and it has an effect.
 - Best foot forward.

I'd like our models to look as nice as Drake can handle (whether they're done with "best texturing practices" is a different issue). For example, I started working on one of the robot arms to use glTF and was actively looking to make the model look better. I think it's worth having a feature request that the models in this repo look as good as possible, as we've implicitly branded them with Drake.

But it's definitely outside the scope of this PR.
</blockquote></details>

Agreed.  I think it's a fine project.  If we can do it with contractor money and hours, all the better.

___
___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfmAr47vlCJd0zKQ0s:b-vaktf) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
> I got the sense that you didn't want to change appearance.

I did want to change the look.  Should I clarify the commit message somehow?

The purpose of this model to support a motion planning benchmarking test.  (It's not used by anything else.)  For watching the benchmark in Meshcat, I judged that the different texture on the base was equally suitable.

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM: X2

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33#-:-NrfogDB2ivx6lwElNgj:bxqo58p)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfojmUC6oIQdHgFiWZ:b6pspfr) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

> I got the sense that you didn't want to change appearance.

I did want to change the look.  Should I clarify the commit message somehow?

The purpose of this model to support a motion planning benchmarking test.  (It's not used by anything else.)  For watching the benchmark in Meshcat, I judged that the different texture on the base was equally suitable.
</blockquote></details>

Nah, I inferred that from the fact that you didn't want to fix the gap in the stack of spacers. Probably reading a bit too much into that. As long as you're content and not worried, I'm good. My primary role is to call things out to confirm we're not doing anything accidentally.  :)

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for platform review per schedule, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

___
*[`tri_homecart/assets/homecart_basecart.gltf` line 88 at r2](https://reviewable.io/reviews/RobotLocomotion/models/33#-NrfB-09ABmIZuHlHVL5:-NrfqW7e3EjD7XUhbJ1x:bsktgli) ([raw file](https://github.com/RobotLocomotion/models/blob/d8b3dc0c11ded371b3002c83901dec4ec16058c4/tri_homecart/assets/homecart_basecart.gltf#L88)):*
> I inferred that from the fact that you didn't want to fix the gap in the stack of spacers.

Ah, yes I can see the confusion now!  On the one hand, I was saying that this PR should be an non-functional change, while with the other hand I was making a texturing change.

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 25 of 28 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/33#-:-Nrg4jmEAhSbyVVQQeQB:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

**Pull request merged**
