### PR TITLE
Convert `iiwa7` and `iiwa14` .obj mesh files to glTF

### PR DESCRIPTION
**Pull request by siddancha**
Related: https://github.com/RobotLocomotion/drake/pull/21079

## Changes

- Replaces  `iiwa7` and `iiwa14` .obj mesh files (visual only, not collision) to `.gltf` + `.bin` files.
  - For example, `link_0.obj` now becomes `link_0.gltf` + `link_0.bin`.
  
- ~~Also adds [draco compressed](https://google.github.io/draco/) versions of the files.~~
  - ~~For example, `link_0.obj` also becomes `link_0.draco.gltf` + `link_0.draco.bin`.~~

## Benefits
- This resolves the issue of IIWA `*.obj` files being duplicated in static HTML: https://github.com/RobotLocomotion/drake/issues/21056

- This also helps reduce the size of `link_0.obj` (620 KB) to
  - `link_0.gltf` (4 KB) + `link_0.bin` (184 K) or
  - ~~`link_0.draco.gltf`  (4 KB) + `link_0.draco.bin` (20 KB)~~

## Visualization
  
 - Here's a visualization of what the IIWA's look like: [[ANIMATION]](https://www.mit.edu/~sancha/kuka-gltf.html):
   

## Conversion process

- The following script was used for conversion using the [obj2gltf](https://github.com/CesiumGS/obj2gltf) ~~and [gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline) tools~~:
  ```bash
  FILES="path/to/*.obj"
  for file in $FILES; do
      obj2gltf -i "${file}" -s --inputUpAxis Z
      # obj2gltf -i "${file}" -o "${file%.obj}.full.gltf" --inputUpAxis Z
      # gltf-pipeline -i "${file%.obj}.full.gltf" -o "${file%.obj}.draco.gltf" -d -s
      # rm "${file%.obj}.full.gltf"
  done
  ```

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/36)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Thanks for this!

At the moment, we can't accept the draco files, even as as separate `*.gltf` files.  We intended to use this repository to showcase the best practices for Drake's model files, and having duplicated `*.gltf` files (depending on the mesh compression) is not a best practice.

Our medium-term aim with draco meshes is to have them as "extentionsUsed" but not "extentionsRequired" in the same gltf file as the uncompressed meshes.  Then consumers that know about draco will use them, but consumers that don't will fall back to the uncompressed mesh.  A kind of "graceful degradation" so that we don't need (for example) separately forked SDFormat files for the two mesh styles.

So I'll ask that for this first PR, please just keep the normal uncompressed meshes and `git rm` the draco ones for now.  Once we have more Drake capabilities and tooling related to draco meshes ready, we can start using draco here.

**Comment by siddancha** [comment]
Makes sense @jwnimmer-tri . Removed all draco-related files.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: so far.

I'm going to look at the Drake PR next.  We'll need to merge them ~concurrently, so for now this one is on pause while I check that one.

> Reviewed 63 of 105 files at r1, 42 of 42 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/36#-:-Nrr1xtXD44H_ksHKzY5:bu0lyj2)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @siddancha)

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/36)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/36#-Nrr2mGn5tcQOUbeFDIQ:-Nrr2mGn5tcQOUbeFDIR:b-iy2c9z) (no related file):*
Reminder for myself to squash when merging into master.

___

**Comment by siddancha** [comment]
@jwnimmer-tri I want to add that I tweaked some material parameters in the glTF files. For one, the original .obj files don't contain any material/color information. I copied the RGB values provided in [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake)'s  [iiwa_description](https://github.com/RobotLocomotion/drake) URDF files. Since material properties in glTF files are more expressive (e.g. `metallicFactor`, `roughnessFactor`), I picked sensible values guided by how aesthetic the iiwas looked in meschat.

**Review by jwnimmer-tri — APPROVED** [review]
Thanks for the help on this, looks good now.

+@rpoyner-tri for platform review, please.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/36#-:-NtcmXrdCukjznRBQUtS:b-tsvsl3)* status: 1 unresolved discussion, LGTM missing from assignee rpoyner-tri, platform LGTM from [jwnimmer-tri] (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 60 of 105 files at r1, 42 of 42 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/36#-:-NtmGsXrA9wSwYtt7KKB:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri, rpoyner-tri] (waiting on @jwnimmer-tri)

**Pull request merged**
