### PR TITLE
skydio 2 model files

### PR DESCRIPTION
**Pull request by RussTedrake**
from @abachrach .

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/models/7)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Also, i followed the pattern of putting the mesh file here, but didn't put the urdf.  I coud potentially move that over, too?  Or provide a copy of it?

**Comment by RussTedrake** [comment]
I’m waiting on the fix to meshcat to land and an AOK from @abachrach on the license before I merge.

**Comment by abachrach** [comment]
License file lgtm. Thanks!

**Comment by EricCousineau-TRI** [comment]
FTR This is for downstream:
https://github.com/robotlocomotion/drake/pull/13050

**Pull request merged**
