### PR TITLE
[homecart] URDF text cleanups

### PR DESCRIPTION
**Pull request by rpoyner-tri**
This file escaped a previous cleanup pass in drake by hiding in models.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/52)

### CODE REVIEW

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/52)* status: 1 unresolved discussion, platform LGTM missing (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/52#-NuPUeIn1iT9HbdE1bUo:-NuPUeIn1iT9HbdE1bUp:bxrehyj) (no related file):*
requires ceremonies described at https://drake.mit.edu/model_version_control.html

___

**Review by rpoyner-tri — COMMENTED** [review]
Matching Drake PR is https://github.com/RobotLocomotion/drake/pull/21230

This patch removes dead urdf text; see also https://github.com/RobotLocomotion/drake/pull/21067 .

+@jwnimmer-tri for both reviews, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/52#-:-NuPZ8DX3TvsZ-hh0Qu1:bv7854k)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm: both.

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/52#-:-NuPjEWu0HE5qKYAoxA9:b-85g6de)* status: 1 unresolved discussion, platform LGTM from [jwnimmer-tri] (waiting on @rpoyner-tri)

**Review by rpoyner-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/52)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @rpoyner-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/52#-NuPUeIn1iT9HbdE1bUo:-NuPuWZhDcTIil905G82:b-qq1trj) (no related file):*
<details><summary><i>Previously, rpoyner-tri (Rick Poyner (rico)) wrote…</i></summary><blockquote>

requires ceremonies described at https://drake.mit.edu/model_version_control.html
</blockquote></details>

https://github.com/RobotLocomotion/drake/pull/21230 has been generally approved.

___

**Pull request merged**
