### PR TITLE
Move hydroelastic models from Drake to here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Twin PR: https://github.com/RobotLocomotion/drake/pull/21244

---
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/57)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@DamrongGuoy for feature review, please.

**Review by DamrongGuoy — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2, 3 of 3 files at r4, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/57#-:-NuW5ut74MawvMnGP3Zp:bg7igkv)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@xuchenhan-tri for platform review per schedule, please.

Note that we'll use a merge commit here, not squash.

**Review by xuchenhan-tri — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, 3 of 3 files at r4, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/57#-:-NuX071T4Z6PixBONQ7i:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [xuchenhan-tri] (waiting on @jwnimmer-tri)

**Pull request merged**
