### PR TITLE
[tri_homecart] Move related Drake files into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
The files were copied as of Drake commit `098ed592`.

Add the missing `LICENSE` text (for non-third-party files).

Adopt the new convention of `assets` for meshes, images, etc.

---

See #32 for some looming tech debt.

Drake PR: https://github.com/RobotLocomotion/drake/pull/21004

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/31)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@zachfang for feature review, please.

**Review by zachfang — COMMENTED** [review]
:lgtm: feature.

> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/31#-:-NrGUvRb58hSXbBMlJau:b-n37teh)* status: 2 unresolved discussions, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`tri_homecart/homecart_bimanual.urdf` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/models/31#-NrGUIZn8sJmtWpiWgHJ:-NrGUIZn8sJmtWpiWgHK:bihle9o) ([raw file](https://github.com/RobotLocomotion/models/blob/92ed9246562caf6a77a4376b74b41eb777b319c8/tri_homecart/homecart_bimanual.urdf#L3)):*
> ```XML
> <?xml version="1.0" ?>
> 
> 
> ```

BTW. The path is "inaccurate:" now after the move. It's an autogenerated file, so not sure if it's worth fixing.



_Code quote:_
```XML
manipulation/models/tri_homecart/homecart_bimanual.urdf.xacro
```
___
*[`tri_homecart/homecart_cutting_board.sdf` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/models/31#-NrGUiiA8LoXXRqHvG66:-NrGUiiA8LoXXRqHvG67:bt118d2) ([raw file](https://github.com/RobotLocomotion/models/blob/92ed9246562caf6a77a4376b74b41eb777b319c8/tri_homecart/homecart_cutting_board.sdf#L3)):*
> ```
> <?xml version="1.0" ?>
> 
> 
> ```

BTW. Ditto.



_Code quote:_
```
manipulation/models/tri_homecart/homecart_cutting_board.sdf.xacro
```

**Review by jwnimmer-tri — COMMENTED** [review]
+@sherm1 for platform review per schedule, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/31#-:-NrGWqzR58QBkzfC5Zyk:bybe5xg)* status: 1 unresolved discussion, LGTM missing from assignee sherm1, platform LGTM missing (waiting on @sherm1 and @zachfang)

___
*[`tri_homecart/homecart_bimanual.urdf` line 3 at r1](https://reviewable.io/reviews/RobotLocomotion/models/31#-NrGUIZn8sJmtWpiWgHJ:-NrGWelU5wsUphvcksjo:bjs1ti1) ([raw file](https://github.com/RobotLocomotion/models/blob/92ed9246562caf6a77a4376b74b41eb777b319c8/tri_homecart/homecart_bimanual.urdf#L3)):*
<details><summary><i>Previously, zachfang wrote…</i></summary><blockquote>

BTW. The path is "inaccurate:" now after the move. It's an autogenerated file, so not sure if it's worth fixing.
</blockquote></details>

Yeah.  I had the choice of keeping the same content as the Drake git hash cited in the commit message, or adjusting the file(s) by running Xacro again.  Given #32 isn't ready yet, I decided not to try running it again since I would probably screw it up.  When we do #32, the files will re-sync.

**Review by sherm1 — APPROVED** [review]
Platform :lgtm:, one ignorable comment

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/31#-:-NrGpTfx3I1d8YAhMcM8:b-m5yaie)* status: 1 unresolved discussion, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

___
*[`tri_homecart/LICENSE` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/models/31#-NrGoJdq6OL2OgKmsO2H:-NrGoJdq6OL2OgKmsO2I:bdo2u5m) ([raw file](https://github.com/RobotLocomotion/models/blob/92ed9246562caf6a77a4376b74b41eb777b319c8/tri_homecart/LICENSE#L1)):*
> ```
> Copyright 2022 Toyota Research Institute
> ```

BTW customary to update the year for new license installations

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/31)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [sherm1] (waiting on @jwnimmer-tri)

___
*[`tri_homecart/LICENSE` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/models/31#-NrGoJdq6OL2OgKmsO2H:-NrGqN4I78N2sTW82Hx9:b-gsi7kq) ([raw file](https://github.com/RobotLocomotion/models/blob/92ed9246562caf6a77a4376b74b41eb777b319c8/tri_homecart/LICENSE#L1)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW customary to update the year for new license installations
</blockquote></details>

The files were authored in 2022.  I am not changing the files here, only moving them.

**Pull request merged**
