### PR TITLE
[tri_homecart] Add KTX2 textures as extensionsUsed

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/37)

### CODE REVIEW

**Review by SeanCurtis-TRI — CHANGES_REQUESTED** [review]
:LGTM: X2

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/37#-:-NtvI86vEcCnmfmbfOjd:bxqo58p)* status: 1 unresolved discussion, platform LGTM from [seancurtis-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/37#-NtvGQTX9hk6UQd7f5bZ:-NtvGQTYEFy1TMQsvSB2:b-lwos07) (no related file):*
The image below highlights the potential cost of ktx2 conversion.

The image on the left is the ktx2 texture image. Note the red splotches on the cutting board (absent from the original png on the right). 

I mention it, not because it torpedos this PR but to highlight the care that needs to be taken and to document the need to refine the conversion process and revisit these textures. Or, failing that, come up with a sense of what kind of policy we want to adopt relative to these kinds of artifacts. We can assume that we're ok with `meshcat` having those artifacts because they won't show up in our render engines. I think there are multiple options available to us. Just as long as we actively choose them. Whatever we do, this might inform the documentation written in #21193.

I'll be playing with this later today anyways. It may well be that a tweak of process gives us loading benefits while preserving a greater amount of image fidelity.



___

**Review by SeanCurtis-TRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/37)* status: 1 unresolved discussion, platform LGTM from [seancurtis-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/37#-NtvGQTX9hk6UQd7f5bZ:-NtvNuY40W6zz1_dPaTQ:b-4s8djp) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The image below highlights the potential cost of ktx2 conversion.

The image on the left is the ktx2 texture image. Note the red splotches on the cutting board (absent from the original png on the right). 

I mention it, not because it torpedos this PR but to highlight the care that needs to be taken and to document the need to refine the conversion process and revisit these textures. Or, failing that, come up with a sense of what kind of policy we want to adopt relative to these kinds of artifacts. We can assume that we're ok with `meshcat` having those artifacts because they won't show up in our render engines. I think there are multiple options available to us. Just as long as we actively choose them. Whatever we do, this might inform the documentation written in #21193.

I'll be playing with this later today anyways. It may well be that a tweak of process gives us loading benefits while preserving a greater amount of image fidelity.


</blockquote></details>

From the PR number, I'm assuming that this was prepped a while ago. I ran the merged `gltf_add_ktx2.py` script this morning on the gltf and got a *much better* .ktx2 file. One without the red splotches (and one that happens to be ever so slightly smaller). Perhaps the new settings have already manifested an improvement?

___

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/37)* status: 1 unresolved discussion, platform LGTM from [seancurtis-tri] (waiting on @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/models/37#-NtvGQTX9hk6UQd7f5bZ:-NtvQEP0-LPdb-ENQMi1:brw5m9p) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

From the PR number, I'm assuming that this was prepped a while ago. I ran the merged `gltf_add_ktx2.py` script this morning on the gltf and got a *much better* .ktx2 file. One without the red splotches (and one that happens to be ever so slightly smaller). Perhaps the new settings have already manifested an improvement?
</blockquote></details>

Yeah, that was on my mind as well.

Would you be so kind as to push the current output of the conversion tool into this PR?  Including any new gltf edits, if relevant.

We'll squash-merge onto master when finished.

___

**Comment by jwnimmer-tri** [comment]
Works for me.

**Pull request merged**
