### PR TITLE
Add TRI Homecart mesh files

### PR DESCRIPTION
**Pull request by RussTedrake**
Relates to https://github.com/RobotLocomotion/drake/pull/17387.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
The `models/tri_homecart/homecart_basecart.obj` is 33 MiB with >250k faces, plus a 5 MiB wooden texture file.  That seems like an overkill level of detail for a visual-only mesh used for a _motion planning_ demo.

Even once we've adjusted our distribution channels to tolerate larger files (e.g. YCB) whether by fetching them at runtime or otherwise, larger files still come come with costs -- more CI time downloading on every build, slower git clones (it's in this repo's git history forever), slower loading when viewing in MeshCat, etc.

If there is a good reason we need a high-resolution visual mesh, that information should appear in one of the PR description(s) to provide context.

I've also posed in Anzu asking about the license file for the Wood texture file.  I don't think we own it.

**Comment by allisonh-tri** [comment]
I am not certain but I think the wood texture file came from Cody based on photos I sent him of the actual cutting board surface, but it may also be that he or someone found a matching texture file based on the photos.

**Review by BenBurchfiel-TRI — COMMENTED** [review]
I believe the texture file came from here: https://ambientcg.com/view?id=Wood049

[The license is:](https://docs.ambientcg.com/books/website-licensing/page/license-information)
```
All ambientCG assets are provided under the
Creative Commons CC0 1.0 Universal License.
This applies to the downloadable asset files and the "preview spheres" (material preview renders) shown on the site.
```
and the textures are labeled as being public domain. If size is an issue we can just down sample it and push a smaller resolution version of the texture file.

It's not required, but it would be polite to give credit via:
```
Created using <asset name> from ambientCG.com, licensed under the Creative Commons CC0 1.0 Universal License.
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18#-:-N5_oBrC4fnVVGD1gfTu:b64p2k0)* status: all discussions resolved, platform LGTM missing

**Comment by BenBurchfiel-TRI** [comment]
Let me tack a crack at decimating the mesh. If results aren't good I'll pass it off to Cody.

**Comment by jwnimmer-tri** [comment]
Looking as Russ' screenshot, I would be surprised (but happy!) if decimation worked.  My intuition is that we will need to nuke the casters, 80/20 guide channels, through-holes, etc. in order to reach a suitable size.  The goal I'd set is the order of ~10x reduction in size.

**Comment by IanTheEngineer** [comment]
> nuke the casters

In general I agree with your assessment, Jeremy, on the practical methods needed for reducing the homecart base mesh size. However, if we remove the casters, they should be replaced with cylinders or boxes to preserve the true homecart height.

**Review by BenBurchfiel-TRI — COMMENTED** [review]
Let's see how the above baseplate renders. The corners are perhaps a bit sketchy so manual cleanup may still be the best route forward.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18#-:-N5atzAx21eIuan-Lpef:b-qolaez)* status: all discussions resolved, platform LGTM missing

**Comment by allisonh-tri** [comment]
FWIW, Cody said he had used a different texture file for the wood (based on photos I sent), not the creative commons one and I think there are a few home-cart models floating around.  There may already be a much more decimated version of the one in question here?  In any case, I asked Cody about this just to give him a heads up and he does have time to help clean it up if automatic decimation isn't perfect.

**Comment by allisonh-tri** [comment]
I mentioned this to Cody to see if he already had a simpler mesh.  This is his response:
I've done a couple of optimization passes on my version of the homecart (removing extraneous bolts, holes, reducing geometry on fillets/bevels, etc.).

The most poly dense area was the wheels, which were about 35k each. I just ended up replacing them with a blockier, lower poly version.

There's still a bit of clean up and fiddling to be done, but the whole setup is currently at 22,790 tris, it should hopefully stay under 25k and it'll be cleaner than decimating.


homecart_geo_optimization_2022-06-28_1

**Review by RussTedrake — COMMENTED** [review]
This looks great to me.  @allisonh-tri -- the last note from Cody says there is more fiddling to do.  Can we perhaps coordinate tomorrow so that I can either land it or understand specifically what I should be waiting for?  I ultimately need a final decision on all of the files (and licenses) for all of the files in this PR.   Thanks!

Btw - @iantheengineer -- thanks for your contributions, too.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18#-:-N6FkVYI9PJnPsVmWD-v:b-10iac6)* status: all discussions resolved, platform LGTM missing

**Comment by allisonh-tri** [comment]
Sure thing!  I told Cody to wait until you confirm you want him to continue.  I'll ask him if he can finish his changes today.  If you'd like he can kick off the PR in Anzu, and/or he can give you the files directly.

**Comment by RussTedrake** [comment]
my goal is to get the files into this PR.  Whatever is easier for Cody to accomplish that (via anzu, on this repo, or direct to me) is fine.  thanks!

**Review by ggould-tri — APPROVED** [review]
From f2f discussion with Russ:  -@rpoyner-tri +@ggould-tri :lgtm: (one nit)

> Reviewed 18 of 32 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18#-:-N6ngiMsEhlzBYwEKBNw:bs5xp65)* status: 1 unresolved discussion, platform LGTM from [ggould-tri] (waiting on @RussTedrake)

___
*[`ur3e/LICENSE.TXT` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/models/18#-N6ng9-j4ZtS_yBZxDnm:-N6ng9-j4ZtS_yBZxDnn:b-klyehi) ([raw file](https://github.com/robotlocomotion/models/blob/083f4d5edc78486a1c82d705ff78213ff066ce96/ur3e/LICENSE.TXT#L1)):*
> ```
>   Per https://github.com/ros-industrial/universal_robot/blob/melodic-devel/ur_description/package.xml
> ```

nit:  all-caps ".TXT" filename is inconsistent with our practice elsewhere (and confuses reviewable's sorting )

**Comment by jwnimmer-tri** [comment]
*[`ur3e/LICENSE.TXT` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/models/18#-N6ng9-j4ZtS_yBZxDnm:-N6nj2Q22mHy6l2bnTty:b-7zzyzr) ([raw file](https://github.com/robotlocomotion/models/blob/083f4d5edc78486a1c82d705ff78213ff066ce96/ur3e/LICENSE.TXT#L1)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

nit:  all-caps ".TXT" filename is inconsistent with our practice elsewhere (and confuses reviewable's sorting )
</blockquote></details>

Is that accurate?

```
jwnimmer@call-cps:~/jwnimmer-tri/drake$ find . -iname 'license.txt'
./LICENSE.TXT
./doc/pydrake/LICENSE.TXT
./doc/third_party/dracula/LICENSE.txt
./doc/third_party/pylons/LICENSE.txt
./doc/third_party/github-styling/LICENSE.txt
./manipulation/models/jaco_description/LICENSE.TXT
./manipulation/models/iiwa_description/LICENSE.TXT
./manipulation/models/franka_description/LICENSE.TXT
./manipulation/models/allegro_hand_description/LICENSE.TXT

jwnimmer@call-cps:~/jwnimmer-tri/models$ find . -iname 'license.txt'
./tri_homecart/LICENSE.TXT
./ycb/meshes/LICENSE.txt
./ur3e/LICENSE.TXT
```

**Review by ggould-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/18)* status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri] (waiting on @RussTedrake)

___
*[`ur3e/LICENSE.TXT` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/models/18#-N6ng9-j4ZtS_yBZxDnm:-N6njm8zBOFaIO_el7Pt:bmuak5w) ([raw file](https://github.com/robotlocomotion/models/blob/083f4d5edc78486a1c82d705ff78213ff066ce96/ur3e/LICENSE.TXT#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Is that accurate?

```
jwnimmer@call-cps:~/jwnimmer-tri/drake$ find . -iname 'license.txt'
./LICENSE.TXT
./doc/pydrake/LICENSE.TXT
./doc/third_party/dracula/LICENSE.txt
./doc/third_party/pylons/LICENSE.txt
./doc/third_party/github-styling/LICENSE.txt
./manipulation/models/jaco_description/LICENSE.TXT
./manipulation/models/iiwa_description/LICENSE.TXT
./manipulation/models/franka_description/LICENSE.TXT
./manipulation/models/allegro_hand_description/LICENSE.TXT

jwnimmer@call-cps:~/jwnimmer-tri/models$ find . -iname 'license.txt'
./tri_homecart/LICENSE.TXT
./ycb/meshes/LICENSE.txt
./ur3e/LICENSE.TXT
```
</blockquote></details>

I meant elsewhere in this same PR.  But point take; objection withdrawn.

**Pull request merged**
