### PR TITLE
Add Schunk with hydroelastic bubble meshes

### PR DESCRIPTION
**Pull request by joemasterjohn**
This PR adds the meshes and mtl files for the Schunk gripper with hydroelastic bubble fingers. 

\cc @EricCousineau-TRI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Per the `README` and `LICENSE` at https://github.com/RobotLocomotion/models/tree/master/wsg_50_description, the `wsg_50_description` folder is only intended to house the meshes representing Schunk products.  TRI's bubble meshes should be housed in a different folder.

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
+@xuchenhan-tri for feature review of the contents of the new files, please.

I'll platform-review the format/rules specific to the models file storage.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17#-:-MwlwingEWqj4kIktC-A:b-8diesp)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee xuchenhan-tri, platform LGTM missing (waiting on @joemasterjohn and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/17#-MwlwQGN7afAW3fpN7Qa:-MwlwQGN7afAW3fpN7Qb:bof9dq7) (no related file):*
Because this repository is a grab-bag of different files, every subdirectory grouping needs its own README and LICENSE files.

Check https://github.com/RobotLocomotion/models/tree/master/dishes/bowls for a good example in the case of TRI-authored files.

---

**Review by xuchenhan-tri — COMMENTED** [review]
:lgtm: with two comments.

 I checked the mesh with Blender. Looks great (though a little too big)!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17#-:-MwnBtfh6nlBRx7NxLog:b-xi0fsu)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @joemasterjohn and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/17#-MwlwQGN7afAW3fpN7Qa:-MwnDHAP0Fi2LIePZpAr:b72h7jb) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Because this repository is a grab-bag of different files, every subdirectory grouping needs its own README and LICENSE files.

Check https://github.com/RobotLocomotion/models/tree/master/dishes/bowls for a good example in the case of TRI-authored files.
</blockquote></details>

These a very fine meshes. Perhaps mention that they are only good for visual meshes (or expect very low sim if used as collision geometries).

---
___
*[wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj, line 0 at r1](https://reviewable.io/reviews/robotlocomotion/models/17#-MwnCqHP5D_V5kS4F3eT:-MwnCqHP5D_V5kS4F3eU:b-lb3b43) ([raw file](https://github.com/robotlocomotion/models/blob/fcb642c0e6f0cb0ac14280f7324eab4466f219e5/wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj#L0)):*
The numbers for the positions of the vertices are very large, and we'd have to scale them when loading in sdf files. Any reasons for this choice of unit?

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @xuchenhan-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/models/17#-MwlwQGN7afAW3fpN7Qa:-Mx1-1KlBwMTb0xtI-Vy:b-ziat5e) (no related file):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

These a very fine meshes. Perhaps mention that they are only good for visual meshes (or expect very low sim if used as collision geometries).
</blockquote></details>

Done. Added the LICENSE and README.md files. PTAL @jwnimmer-tri 

---
___
*[wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/models/17#-MwnCqHP5D_V5kS4F3eT:-Mx0yaBX640ILQovKMYW:bmjfl8c) ([raw file](https://github.com/robotlocomotion/models/blob/fcb642c0e6f0cb0ac14280f7324eab4466f219e5/wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj#L)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The numbers for the positions of the vertices are very large, and we'd have to scale them when loading in sdf files. Any reasons for this choice of unit?
</blockquote></details>

Not sure really, my guess is just default units in whatever modeling program the original author used. I'd scale them to match the real world spec for the punyo bubble, but I'd rather keep the file as in sync with Anzu as possible.

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @joemasterjohn)

___
*[wsg_50_hydro_bubble/LICENSE, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/models/17#-Mx18EUyDD45PK58FWqA:-Mx18EUyDD45PK58FWqB:b7yomgd) ([raw file](https://github.com/robotlocomotion/models/blob/b5532f35237e1749724ae769a363e505cbbf2223/wsg_50_hydro_bubble/LICENSE#L1)):*
> ```
> Copyright 2020 Toyota Research Institute
> ```

nit Just to check -- is this the year that we created these meshes?  A quick peek at Anzu seems like 2019 (in `c1896ab`).



_Code quote:_
```
2020
```
___
*[wsg_50_hydro_bubble/README.md, line 14 at r2](https://reviewable.io/reviews/robotlocomotion/models/17#-Mx19AvF27zUrmgCJhZ-:-Mx19AvF27zUrmgCJhZ0:bdrj24l) ([raw file](https://github.com/robotlocomotion/models/blob/b5532f35237e1749724ae769a363e505cbbf2223/wsg_50_hydro_bubble/README.md#L14)):*
When modeling meshes for robot parts from other vendors, here is the summary of what TRI is permitted to do, as I understand it:

> We can create our own functional representation of the gripper and fingers with our own meshes based on information in drawings etc., but we need to stick to functional attributes only (for example, collision volumes for space claims) and not copy the artistic / aesthetic attributes of the gripper and fingers.

This model is too detailed, per the above.

Can you change the example programs SDFormat file to refer to package://drake/manipulation/models/wsg_50_description/meshes/wsg_body.obj, instead of this new mesh (and remove the bubble_gripper_base.mtl from this PR)?
___
*[wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/models/17#-MwnCqHP5D_V5kS4F3eT:-Mx17yy1DUNPeLiy4OxK:brtfyjf) ([raw file](https://github.com/robotlocomotion/models/blob/fcb642c0e6f0cb0ac14280f7324eab4466f219e5/wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj#L)):*
<details><summary><i>Previously, joemasterjohn (Joe Masterjohn) wrote…</i></summary><blockquote>

Not sure really, my guess is just default units in whatever modeling program the original author used. I'd scale them to match the real world spec for the punyo bubble, but I'd rather keep the file as in sync with Anzu as possible.
</blockquote></details>

FYI I don't remember the back-story anymore, but for whatever reason it seems common for CAD modeling artists to work in millimeters.

**Review by xuchenhan-tri — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @joemasterjohn)

___
*[wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj, line  at r1](https://reviewable.io/reviews/robotlocomotion/models/17#-MwnCqHP5D_V5kS4F3eT:-Mx1CKQK9BRg7q9IGj2s:b5w0o00) ([raw file](https://github.com/robotlocomotion/models/blob/fcb642c0e6f0cb0ac14280f7324eab4466f219e5/wsg_50_hydro_bubble/meshes/bubble_gripper_base.obj#L)):*
> I'd rather keep the file as in sync with Anzu as possible.

Makes sense. Marking myself satisfied. @jwnimmer-tri thanks for the info.

**Review by joemasterjohn — COMMENTED** [review]
-@sherm1 sorry, wrong PR,

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17#-:-Mx5CFOz8a3IGHt-Koti:bdxwafc)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @joemasterjohn)

**Review by joemasterjohn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri and @xuchenhan-tri)

___
*[wsg_50_hydro_bubble/LICENSE, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/models/17#-Mx18EUyDD45PK58FWqA:-Mx5DFAKCMJDp6XO5h9j:b-ucl3er) ([raw file](https://github.com/robotlocomotion/models/blob/b5532f35237e1749724ae769a363e505cbbf2223/wsg_50_hydro_bubble/LICENSE#L1)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Just to check -- is this the year that we created these meshes?  A quick peek at Anzu seems like 2019 (in `c1896ab`).
</blockquote></details>

Done. 2019 seems to be the correct year, yes.
___
*[wsg_50_hydro_bubble/README.md, line 14 at r2](https://reviewable.io/reviews/robotlocomotion/models/17#-Mx19AvF27zUrmgCJhZ-:-Mx5JSM0AMLNXpaGBISS:b-2t6p9k) ([raw file](https://github.com/robotlocomotion/models/blob/b5532f35237e1749724ae769a363e505cbbf2223/wsg_50_hydro_bubble/README.md#L14)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

When modeling meshes for robot parts from other vendors, here is the summary of what TRI is permitted to do, as I understand it:

> We can create our own functional representation of the gripper and fingers with our own meshes based on information in drawings etc., but we need to stick to functional attributes only (for example, collision volumes for space claims) and not copy the artistic / aesthetic attributes of the gripper and fingers.

This model is too detailed, per the above.

Can you change the example programs SDFormat file to refer to package://drake/manipulation/models/wsg_50_description/meshes/wsg_body.obj, instead of this new mesh (and remove the bubble_gripper_base.mtl from this PR)?
</blockquote></details>

Done. I've changed the example to use the simplified mesh and removed the detailed mesh from this PR.

**Review by jwnimmer-tri — APPROVED** [review]
This LGTM now.  Once the Drake PR is closer to its final form, I'll merge this so that you can finalize the Drake PR.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17#-:-Mx5KW9E-mmY5Nh4MDaK:b-4391v3)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @joemasterjohn)

**Comment by jwnimmer-tri** [comment]
:lgtm: here.  It seems like the Drake PR reviewers are happy with these meshes in their current form.

**Comment by jwnimmer-tri** [comment]
:lgtm_cancel: oops, one moment.

**Comment by jwnimmer-tri** [comment]
Apparently this repository doesn't have "squash and merge" enabled.  Could you please force-push a rebased branch using a single commit with a finalized commit message?

**Review by joemasterjohn — COMMENTED** [review]
Ok, done.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/models/17#-:-Mx6ASAq-4bDCU9jReiG:bl1h72v)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm: merging now.

**Pull request merged**
