### PR TITLE
Move many related Drake files into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Packages moved here:
- franka_description
- iiwa_description
- jaco_description
- ur_description
- wsg_50_description

Towards #44 and https://github.com/RobotLocomotion/drake/issues/13942.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21218.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 21 of 21 files at r2, 10 of 10 files at r3, 18 of 18 files at r4, 1 of 1 files at r5, 4 of 5 files at r6, 1 of 3 files at r7, 3 of 3 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48)* status: all discussions resolved, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
+@rpoyner-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48#-:-NuPvXu94vEtE0HpgNAw:b95uado)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

___
*[`ur3e` line 1 at r10](https://reviewable.io/reviews/RobotLocomotion/models/48#-NuPxeZL8M38-rVuLlVi:-NuPxeZL8M38-rVuLlVj:bd906pc) ([raw file](https://github.com/RobotLocomotion/models/blob/285eddb2ee8fe033eb9e6a2e2088e1163e83dc06/ur3e#L1)):*
> ```
> ur_description/meshes
> ```

FYI https://github.com/RobotLocomotion/models/issues/49

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 21 of 21 files at r2, 10 of 10 files at r3, 18 of 18 files at r4, 1 of 1 files at r5, 5 of 5 files at r6, 3 of 3 files at r7, 3 of 3 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48#-:-NuQ93j_570Ih9WMiwfG:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

___
*[`iiwa_description/urdf/iiwa14.xacro` line 42 at r2](https://reviewable.io/reviews/RobotLocomotion/models/48#-NuPxY3l4YdHv984_zb3:-NuPxY3l4YdHv984_zb4:b-frkiya) ([raw file](https://github.com/RobotLocomotion/models/blob/7a53b9e303a9447a010470fcab0213093adfcc73/iiwa_description/urdf/iiwa14.xacro#L42)):*
> ```XML
>             <mesh filename="package://drake_models/iiwa_description/meshes/iiwa14/collision/link_0.obj"/>
>           </geometry>
>           <material name="Grey"/>
> ```

nit collision/material is dead code; i've generally been deleting it. Not sure why these didn't get caught. perhaps the if conditions didn't trigger, or something.

**Review by rpoyner-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/48)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Sigh.  I forgot to wait for platform review on this PR.  Our Reviewable interlock doesn't enforce it.

**Pull request merged**
