### PR TITLE
wsg_50 mesh files added

### PR DESCRIPTION
**Pull request by hjsuh94**
From Drake PR: https://github.com/RobotLocomotion/drake/pull/13922

This PR submits the mesh portion of the new WSG-50 visualization.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/models/13)

### CODE REVIEW

**Comment by hjsuh94** [comment]
@RussTedrake for review please!

**Comment by jwnimmer-tri** [comment]
> ... converted from the original CAD files downloaded from the Schunk's website on WSG 050-110-P mode ...

Could you please post here under what license (that permits redistribution) those CAD files were offered under at the website?  I pulled up the URL from this README but wasn't able to see it in the first click or two.  All I found was a form where it would email me the CAD files -- if that's how you got them, maybe the email contained redistribution info?

**Comment by hjsuh94** [comment]
Thank you @sammy-tri  and @jwnimmer-tri !

I'm still trying to look for what the exact license files are - so far I'm kind of lost, but I think you are right this file is from PARTcommunity, and their terms of use file did refer to the Cadenas terms of use. 

One workaround is we just CAD our own files from the drawings on Schunk's website, such as their product catalog posted here:
https://schunk.com/fileadmin/pim/docs/IM0026091.PDF

that way we have nothing to do with Cadenas. But what are the licenses on Schunk's drawings??

**Comment by hjsuh94** [comment]
@sammy-tri @jwnimmer-tri I created a CAD myself from Schunk's drawing file as opposed to downloading them from CADENAS, and the corresponding LICENSE file has been included in the directory. 

Let me know if it looks good to merge!

**Comment by jwnimmer-tri** [comment]
Either the dimensioned drawings came with a license file that we reproduce here and credit to Schunk GmbH, or they did not and the `LICENSE` file in this PR must not give Schunk GmbH as a copyright owner -- only your employer is the owner, since _you_ created the files here.  If Schunk GmbH is a copyright owner, we must copy only under their terms; your claim is that they are not an owner, and so you don't have to follow any particular license of theirs.

As for whether creating a mesh file from a dimensioned drawing is copyright infringement, I'd be curious to hear your take on whether any of this advice applies: http://patentonomy.blogspot.com/2012/06/copyright-protection-for-mechanical.html.

Of course, I am not a lawyer and neither is "googling it".  I really have no idea how to try to legally create a mesh of a robot where the vendor does not provide for redistributable meshes in the first place.  We should ask a real lawyer, and/or ask Schunk to release the data under a FOSS license.

**Comment by hjsuh94** [comment]
@jwnimmer-tri Thank you for the feedback! 

This is getting confusing - the drawings definitely have Schunk's copyright on it (but no clear license), so it somehow seems like while I made this file, it is still their copyright? 

I agree it is useless to guess - the fastest way must be to contact a lawyer, or Schunk directly so we have a clean solution to this. 

@RussTedrake it looks like this PR might take a while due to strange legal issues!

**Comment by jwnimmer-tri** [comment]
> ... it somehow seems like while I made this file, it is still their copyright?

If you transcribed the dimensioned drawing into another dimensioned drawing with the original drawing "by your left elbow", I believe that would be infringement.  As to whether a mesh transcription is also infringing, I cannot be sure.  It might be sufficient to move forward.  Notably a third option beyond "ask a lawyer" and "ask Shunk for permission" would be "Russ blesses it as sufficient".  It's above my pay grade, though.

**Comment by hjsuh94** [comment]
Done - Schunk's copyright line has been removed!

**Comment by hjsuh94** [comment]
Per conversation with @jwnimmer-tri , all aesthetic components have been deleted and the meshes have been reduced down to necessary functional components. 

Screenshot from 2020-08-27 15-15-54
Screenshot from 2020-08-27 15-16-31

**Comment by jwnimmer-tri** [comment]
This all looks good to me, including the README and LICENSE.  I'll let @sammy-tri double check.

**Pull request merged**
