### PR TITLE
[ycb] Move related Drake files into here

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This were copied from Drake as of `1d54460b`.

Twin PR: https://github.com/RobotLocomotion/drake/pull/21190

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/42)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for both reviews, please (load balancing Rico).

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM: X2

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/42#-:-NtrWALpB7MpcjKmVC5Z:bxqo58p)* status: 1 unresolved discussion, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/models/42#-NtrVa1t9vz3yBLjGD0R):*
nit: typo



_Suggestion:_
```
These
```

**Review by SeanCurtis-TRI — APPROVED** [review]
(BTW, Apparently I don't have platform review powers over here.)

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/42#-:-NtrWDRi1FlUeAfsjhjg:biy7wq5)* status: 1 unresolved discussion, platform LGTM missing (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
> (BTW, Apparently I don't have platform review powers over here.)

Fixed.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/42)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [seancurtis-tri] (waiting on @jwnimmer-tri)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/RobotLocomotion/models/42#-NtrVa1t9vz3yBLjGD0R):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Will fix during squashing.

**Pull request merged**
