### PR TITLE
Asset for tutorial: hydroelastic nonconvex meshes

### PR DESCRIPTION
**Pull request by DamrongGuoy**
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/29)

### CODE REVIEW

**Review by DamrongGuoy — COMMENTED** [review]
The companion Drake PR is https://github.com/RobotLocomotion/drake/pull/20774.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/29#-:-NoKOHQwBkr9a0lPup5b:bjofjyh)* status: all discussions resolved, platform LGTM missing

**Review by DamrongGuoy — COMMENTED** [review]
+@rpoyner-tri for feature review, please.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/29#-:-NrICl4i59FfQ3CxZ4dk:blnrywe)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @rpoyner-tri)

**Review by rpoyner-tri — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/29)* status: all discussions resolved, LGTM missing from assignee rpoyner-tri, platform LGTM missing (waiting on @DamrongGuoy)

**Review by rpoyner-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/models/29#-:-NrMtEPb3L6qXrSTfh5v:bnfp4nl)* status: <span>:shipit:</span> complete! all discussions resolved, platform LGTM from [rpoyner-tri] (waiting on @DamrongGuoy)

**Pull request merged**
